# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.9.0
  # 版权年份
  copyrightYear: 2025
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: ${UPLOAD_PATH:/home/ruoyi/uploadPath}
  # 获取ip地址开关
  addressEnabled: true
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8090
  servlet:
    # 应用的访问路径
    context-path: /
    # session最大超时时间(分钟)，默认为30
    session:
      timeout: 1800
  # Tomcat配置
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    # 最大连接数
    max-connections: 8192
    # 最大参数数量（解决FileCountLimitExceededException）
    max-parameter-count: 50000
    # 最大HTTP表单POST大小（注意：SpringBoot 2.5需要使用字节数）
    max-http-form-post-size: 62914560  # 60MB
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.musicmanager: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 50MB
      # 设置总上传的文件大小
      max-request-size: 60MB
      # 文件大小阈值
      file-size-threshold: 0
      # 临时文件位置
      location: ${java.io.tmpdir}
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: ${REDIS_HOST:localhost}
    # 端口，默认为6379
    port: ${REDIS_PORT:6379}
    # 数据库索引
    database: ${REDIS_DB:0}
    # 密码
    password: ${REDIS_PASSWORD:}
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: ${JWT_SECRET:your_jwt_secret_key_here_should_be_at_least_64_characters_long}
  # 令牌有效期（默认30分钟）
  expireTime: ${JWT_EXPIRATION:60}

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.musicmanager.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: ${SWAGGER_ENABLED:false}
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice,/system/user/profile/avatar,/system/qlMusic/upload,/common/upload
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 音乐上传配置
music:
  upload:
    # 允许的音乐文件类型
    allowed-music-types: mp3,wav,flac,m4a,aac,ogg
    # 允许的封面文件类型
    allowed-cover-types: jpg,jpeg,png,gif,webp
    # 最大音乐文件大小（字节）
    max-music-size: 52428800  # 50MB
    # 最大封面文件大小（字节）
    max-cover-size: 2097152   # 2MB
    # 音乐文件上传路径
    music-path: ${MUSIC_UPLOAD_PATH:/uploads/music/}
    # 封面文件上传路径
    cover-path: ${COVER_UPLOAD_PATH:/uploads/covers/}

# 阿里云OSS配置
oss:
  enabled: true
  endpoint: ${OSS_ENDPOINT:oss-cn-hangzhou.aliyuncs.com}
  access-key-id: ${OSS_ACCESS_KEY_ID:your_access_key_id}
  access-key-secret: ${OSS_ACCESS_KEY_SECRET:your_access_key_secret}
  bucket-name: ${OSS_BUCKET_NAME:your-bucket-name}
  # 音乐文件存储前缀
  music-prefix: ${OSS_MUSIC_PREFIX:music/music-data/}
  # 封面图片存储前缀
  cover-prefix: ${OSS_COVER_PREFIX:music/cover/}
  # Banner图片存储前缀
  banner-prefix: ${OSS_BANNER_PREFIX:music/banner/}
